version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: insta
      POSTGRES_USER: insta
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7

  rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
    volumes:
      - ./nginx-rtmp.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on: [db, redis, rtmp]
    env_file: .env
    ports:
      - "8000:8000"

  worker:
    build: .
    command: celery -A core worker -l info
    depends_on: [redis, db]
    env_file: .env

  beat:
    build: .
    command: celery -A core beat -l info
    depends_on: [redis]

volumes:
  pgdata: